name: mlr container
description: prepare mlr container
runs:
  using: "composite"
  steps:
    - name: hash for podman image
      id: podman_image_hash
      run: |
        echo "::set-output name=value::$(/bin/find bin .github -type f -exec md5sum {} \; | sort -k 2 | md5sum)"
      shell: bash
    - uses: actions/cache@v2
      with:
        path: podman
        key: ${{ runner.os }}-podman-${{ steps.podman_image_hash.outputs.value }}

    - name: prepare mlr image
      shell: bash
      run: |
        set -exuo pipefail
        if [ ! -f podman/mlr.tar ]; then
          bin/install-on-ubuntu
          mkdir -p podman
          sudo podman export mlr > podman/mlr.tar
          sudo podman commit mlr mlr
          sudo podman rm -f mlr
        else
          sudo podman import podman/mlr.tar localhost/mlr
        fi

    - name: prepare mlr container
      shell: bash
      run: |
        sudo podman run -v .:/opt/mailur --name mlr -d mlr /sbin/init

        cat << EOF | sudo podman exec -i -w /opt/mailur mlr /bin/bash
        set -exuo pipefail

        systemctl disable dnf-makecache.timer

        bin/install
        bin/install-test
        EOF
