#!/usr/bin/env python
import json
import pathlib

root = pathlib.Path(__file__).parent

text = (root / 'selection.json').read_text()
icons = json.loads(text)['icons']
tpl = '''\
/* Generated by "assets/font/gen.py" */
:root {
%(icons)s\
}
'''
icon_tpl = '''\
  --symbol--%(name)s {
    &::before {
      content: "\\%(symbol)s";
    }
  }

  --icon--%(name)s {
    @apply --icon;
    @apply --symbol--%(name)s;
  }
'''

css = []
for i in icons:
    name = i['properties']['name']
    code = i['properties']['code']
    symbol = hex(code)[2:]
    css.append(icon_tpl % {'name': name, 'symbol': symbol})

f = (root / 'icons.css').resolve()
f.write_text(tpl % {'icons': '\n'.join(css)})
print('%s updated' % f)
